services:
  dotnet-api-1:
    image: dotnet-api-1
    container_name: dotnet-api-1
    build:
      context: src
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "8080:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DefaultConnection=Host=db_server;Port=5432;Database=stocks_db;Username=postgres;Password=postgres

  database:
    container_name: db_server
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocks_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata1:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  dbdata1: